# Generated by Django 5.2.4 on 2025-12-10 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0002_affiliatelink_vehiclesubmission_tyresize_alt_size_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TyrePressureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_front', models.CharField(max_length=10, verbose_name='Standard Front Pressure')),
                ('standard_rear', models.CharField(max_length=10, verbose_name='Standard Rear Pressure')),
                ('cold_front', models.CharField(blank=True, max_length=10, verbose_name='Cold Front Pressure')),
                ('cold_rear', models.CharField(blank=True, max_length=10, verbose_name='Cold Rear Pressure')),
                ('hot_front', models.CharField(blank=True, max_length=10, verbose_name='Hot Front Pressure')),
                ('hot_rear', models.CharField(blank=True, max_length=10, verbose_name='Hot Rear Pressure')),
                ('light_load_front', models.CharField(blank=True, max_length=10, verbose_name='Light Load Front')),
                ('light_load_rear', models.CharField(blank=True, max_length=10, verbose_name='Light Load Rear')),
                ('full_load_front', models.CharField(blank=True, max_length=10, verbose_name='Full Load Front')),
                ('full_load_rear', models.CharField(blank=True, max_length=10, verbose_name='Full Load Rear')),
                ('max_front', models.CharField(blank=True, max_length=10, verbose_name='Maximum Front Pressure')),
                ('max_rear', models.CharField(blank=True, max_length=10, verbose_name='Maximum Rear Pressure')),
                ('summer_adjustment', models.CharField(default='-2 PSI', max_length=10, verbose_name='Summer Adjustment')),
                ('winter_adjustment', models.CharField(default='+2 PSI', max_length=10, verbose_name='Winter Adjustment')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pressure_data', to='tyres.vehicle')),
            ],
            options={
                'verbose_name': 'Tyre Pressure Data',
                'verbose_name_plural': 'Tyre Pressure Data',
            },
        ),
    ]
