# Generated by Django 6.0 on 2025-12-08 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('category', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('SCOOTER', 'Scooter')], max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['brand', 'model', 'year'],
            },
        ),
        migrations.CreateModel(
            name='TyreSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_size', models.CharField(blank=True, max_length=20, verbose_name='Front Tyre Size')),
                ('front_width', models.IntegerField(blank=True, null=True, verbose_name='Front Width (mm)')),
                ('front_aspect_ratio', models.IntegerField(blank=True, null=True, verbose_name='Front Aspect Ratio (%)')),
                ('front_rim', models.IntegerField(blank=True, null=True, verbose_name='Front Rim Diameter (inches)')),
                ('front_pressure', models.CharField(blank=True, max_length=20, verbose_name='Front Pressure (PSI)')),
                ('rear_size', models.CharField(blank=True, max_length=20, verbose_name='Rear Tyre Size')),
                ('rear_width', models.IntegerField(blank=True, null=True, verbose_name='Rear Width (mm)')),
                ('rear_aspect_ratio', models.IntegerField(blank=True, null=True, verbose_name='Rear Aspect Ratio (%)')),
                ('rear_rim', models.IntegerField(blank=True, null=True, verbose_name='Rear Rim Diameter (inches)')),
                ('rear_pressure', models.CharField(blank=True, max_length=20, verbose_name='Rear Pressure (PSI)')),
                ('tyre_size', models.CharField(blank=True, max_length=20, verbose_name='Tyre Size (if same)')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tyres', to='tyres.vehicle')),
            ],
        ),
    ]
