# Generated by Django 5.2.4 on 2025-12-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link_type', models.CharField(choices=[('TYRE', 'Tyre Retailer'), ('TOOL', 'Tool Retailer'), ('SERVICE', 'Service Center')], max_length=10)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(blank=True, max_length=15)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('category', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('SCOOTER', 'Scooter')], max_length=10)),
                ('front_size', models.CharField(blank=True, max_length=20)),
                ('rear_size', models.CharField(blank=True, max_length=20)),
                ('tyre_size', models.CharField(blank=True, max_length=20)),
                ('front_pressure', models.CharField(blank=True, max_length=20)),
                ('rear_pressure', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(blank=True, help_text='Where did you get this information?', max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tyresize',
            name='alt_size_1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Alternative Size 1'),
        ),
        migrations.AddField(
            model_name='tyresize',
            name='alt_size_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Alternative Size 2'),
        ),
        migrations.AddField(
            model_name='tyresize',
            name='alt_size_3',
            field=models.CharField(blank=True, max_length=20, verbose_name='Alternative Size 3'),
        ),
        migrations.AddField(
            model_name='tyresize',
            name='load_index',
            field=models.CharField(blank=True, max_length=10, verbose_name='Load Index'),
        ),
        migrations.AddField(
            model_name='tyresize',
            name='ply_rating',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ply Rating'),
        ),
        migrations.AddField(
            model_name='tyresize',
            name='pressure_cold_front',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cold Front Pressure'),
        ),
        migrations.AddField(
            model_name='tyresize',
            name='pressure_cold_rear',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cold Rear Pressure'),
        ),
        migrations.AddField(
            model_name='tyresize',
            name='pressure_hot_front',
            field=models.CharField(blank=True, max_length=20, verbose_name='Hot Front Pressure'),
        ),
        migrations.AddField(
            model_name='tyresize',
            name='pressure_hot_rear',
            field=models.CharField(blank=True, max_length=20, verbose_name='Hot Rear Pressure'),
        ),
        migrations.AddField(
            model_name='tyresize',
            name='pressure_loaded_front',
            field=models.CharField(blank=True, max_length=20, verbose_name='Loaded Front Pressure'),
        ),
        migrations.AddField(
            model_name='tyresize',
            name='pressure_loaded_rear',
            field=models.CharField(blank=True, max_length=20, verbose_name='Loaded Rear Pressure'),
        ),
        migrations.AddField(
            model_name='tyresize',
            name='speed_rating',
            field=models.CharField(blank=True, max_length=5, verbose_name='Speed Rating'),
        ),
        migrations.AddField(
            model_name='tyresize',
            name='tube_type',
            field=models.CharField(blank=True, choices=[('TUBE', 'Tube Type'), ('TUBELESS', 'Tubeless'), ('BOTH', 'Both')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tyresize',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
